version: '3.8'

services:
  # Development service
  frontend-dev:
    build:
      context: .
      target: deps
      dockerfile: Dockerfile
    image: converter/frontend-fastapi:v1.0
    container_name: converter-frontend-fastapi-v1.0
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    env_file:
      - .env.local

  # Production service
  frontend-prod:
    build:
      context: .
      target: runner
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.local
    restart: unless-stopped 